### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by lopiyi** [huawei-noah/Efficient-Computing#125]
Training start...

     Epoch  iou_loss  dfl_loss  cls_loss
  0%|          | 0/433 [00:00<?, ?it/s]                                         ERROR in training steps: Default process group has not been initialized, please make sure to call init_process_group.
  0%|          | 0/433 [00:01<?, ?it/s]                                         
ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "E:\Pycharm\Gold-YOLO\tools\train.py", line 129, in <module>
    main(args)
  File "E:\Pycharm\Gold-YOLO\tools\train.py", line 119, in main
    trainer.train()
  File "E:\Pycharm\Gold-YOLO\yolov6\core\engine.py", line 109, in train
    self.train_in_loop(self.epoch)
  File "E:\Pycharm\Gold-YOLO\yolov6\core\engine.py", line 127, in train_in_loop
    self.print_details()
  File "E:\Pycharm\Gold-YOLO\yolov6\core\engine.py", line 339, in print_details
    self.mean_loss = (self.mean_loss * self.step + self.loss_items) / (self.step + 1)
TypeError: unsupported operand type(s) for +: 'Tensor' and 'NoneType'

以上是完整报错内容，大致定位是ERROR in training steps: Default process group has not been initialized, please make sure to call init_process_group.环境是win11，不知如何修改，感谢作者指点！！

**Comment by lose4578** [comment]
You can refer this issue #67
