### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by QiqLiang** [huawei-noah/Efficient-Computing#82]
你好，我在testing的时候用的是coco数据集，格式就是传统的coco数据集格式（annotations, val2017, train2017这几个文件夹），并且设定了--data data/coco.yaml这一参数，但是回报以下错误：
Traceback (most recent call last):
  File "tools/eval.py", line 164, in <module>
    main(args)
  File "tools/eval.py", line 159, in main
    run(**vars(args))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "tools/eval.py", line 149, in run
    dataloader = val.init_data(dataloader, task)
  File "/root/Detection/Gold-YOLO/yolov6/core/evaler.py", line 103, in init_data
    dataloader = create_dataloader(self.data[task if task in ('train', 'val', 'test') else 'val'],
  File "/root/Detection/Gold-YOLO/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/root/Detection/Gold-YOLO/yolov6/data/datasets.py", line 68, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/root/Detection/Gold-YOLO/yolov6/data/datasets.py", line 277, in get_imgs_labels
    assert osp.exists(label_dir), f"{label_dir} is an invalid directory path!"
AssertionError: ../../labels/val2017 is an invalid directory path!
请问是什么原因呢，要怎么解决？谢谢！

**Comment by lose4578** [comment]
It looks like the data path has some problem, maybe you can use the absolute path of your data in coco.yaml.
