### ISSUE TITLE
How should I visualize the results

### ISSUE THREAD

**Issue by Augestern-L** [huawei-noah/Efficient-Computing#89]
How should I visualize the results

**Comment by 18222why** [comment]
you can use tensorboard

**Comment by lose4578** [comment]
And you can run tools/infer.py to visualize the bbox.

**Comment by yaosx425** [comment]
> And you can run tools/infer.py to visualize the bbox.
您好！我运行了infer.py 但是报错两个参数不存在 但是两个参数都是有值的 这是怎么回事呢？

img_size---------------------------------------
[640, 640]
half-------------------------------------------
False
Traceback (most recent call last):
  File "tools/infer.py", line 120, in <module>
    main(args)
  File "tools/infer.py", line 115, in main
    run(**vars(args))
  File "/data2/shuxuan_anaconda/envs/gold/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/infer.py", line 107, in run
    inferer = Inferer(source, weights, device, yaml, img_size, half)
TypeError: __init__() missing 2 required positional arguments: 'img_size' and 'half'

**Comment by lose4578** [comment]
This problem has been fixed.
